server:
  command: "php psr-worker.php"

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 4

reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      dirs: ["."]
      recursive: true
